[tool.ruff]
line-length = 120
target-version = "py39"
select = ["E", "F", "I", "B"]
ignore = [
  # Long lines okay in UI layout and strings
  "E501",
]

[tool.ruff.isort]
known-first-party = ["app"]
force-single-line = false
combine-as-imports = true

[tool.mypy]
python_version = "3.9"
warn_return_any = false  # Temporarily disable to allow app modules to pass
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

[[tool.mypy.overrides]]
module = [
  "Foundation",
  "AppKit", 
  "objc",
  "PyObjCTools",
  "Cocoa"
]
ignore_missing_imports = true

